POST http://localhost:3000/customers/4/baskets

###

PATCH http://localhost:3000/customers/4/baskets/products/2
content-type: application/json

{ "amount": 1000 }

###

GET http://localhost:3000/customers/4/baskets

###

DELETE http://localhost:3000/customers/3/baskets/products/1
content-type: application/json

{ "amount": 500 }

###

GET http://localhost:3000/products

###

GET http://localhost:3000/products/categories

###

###

GET http://localhost:3000/products/4
