const pokeTypes = {
	grass: "grass",
	poison: "poison",
	fire: "fire",
	water: "water",
	electric: "electric",
	ground: "ground",
	psychic: "psychic",
	rock: "rock",
	bug: "bug",
	flying: "flying",
	dragon: "dragon",
	normal: "normal"
}


const pokemonAll = [
    { name: "Bulbasaur",
      type: [pokeTypes.grass, pokeTypes.poison],
      size: 0.7,
      price: 40000,
      info: "Your new best friend. A basic grass pokemon who will follow you through thick and thin"
    },
    { name: "Charmander",
      type: [pokeTypes.fire],
      size: 0.6,
      price: 10000,
      info: "Your new best friend. A basic fire pokemon who will follow you through thick and thin."
    },
    { name: "Squirtle",
      type: [pokeTypes.water],
      size: 0.5,
      price: 10000,
      info: "Do you like going to the beach? Bring your new friend Squirtle!"
    },
    { name: "Pikachu",
      type: [pokeTypes.electric],
      size: 0.4,
      price: 10000,
      info: "Do you need energy? Pikachu can make your days electric!"
    },
    { name: "Nidoqueen",
      type: [pokeTypes.poison, pokeTypes.ground],
      size: 1.3,
      price: 20000,
      info: "Yas, queen! Nidoqueen is back in stock and ready to rumble.",
    },
    { name: "Slowpoke",
      type: [pokeTypes.water, pokeTypes.psychic],
      size: 1.2,
      price: 42000,
      info: "Are you lazy? Like to sleep in? But you'd like some company in your nesting? Buy Slowpoke!",
    },
    { name: "Psyduck",
      type: [pokeTypes.water],
      size: 0.8,
      price: 999,
      info: "Do you like taking care of others, then buy a Psyduck. It needs constant attention to prevent its headaches!",
    },
    { name: "Mewtwo",
      type: [pokeTypes.psychic],
      size: 2,
      price: 200000,
      info: "Our most expensive Pokémon which will make you famous and powerful.",
    },
    { name: "Diglett",
      type: [pokeTypes.ground],
      size: 0.2,
      price: 100,
      info: "Cheap wormy Pokémon. Not good for anything, but kinda entertaning. Consider buying 10, a hammer and you can build your own game of Whack'a'mole.",
    },
    { name: "Voltorb",
      type: [pokeTypes.electric, pokeTypes.grass],
      size: 0.5,
      price: 5000,
      info: "Looks like a pokéball, acts like a Pokémon, what's not to like? Buy it now!",
    },
    { name: "Onix",
      type: [pokeTypes.rock, pokeTypes.ground],
      size: 8.8,
      price: 800000,
      info: "Beautiful, rocky, wormy Onix. Imagine how amazing you'd look taking your Onix for a walk. Buy it before your neighbor!",
    },
    { name: "Meowth",
      type: [pokeTypes.normal],
      size: 0.4,
      price: 8000,
      info: "Loving and caring Pokémon always ready to cuddle. Maybe you are lucky and buy a Meowth which can talk hooman?",
    },
    { name: "Scyther",
      type: [pokeTypes.bug, pokeTypes.flying],
      size: 1.5,
      price: 20000,
      info: "Scyther is the perfect gardener. Buy it and you never have to cut another straw of grass!",
    },
    { name: "Ditto",
      type: [pokeTypes.normal],
      size: 0.3,
      price: 100000,
      info: "Cannot decide which Pokémon to buy? Buy 'em all, by just bying Ditto! Ditto can turn into any Pokémon at any time.",
    },
    { name: "Dragonite",
      type: [pokeTypes.dragon],
      size: 2.2,
      price: 90000,
      info: "Dragonite is fun. Dragonite is cute. Dragonite is ready to move in with you! Buy it before your mom does.",
    },
]




export const pokeColours = {
	normal: '#A8A77A',
	fire: '#EE8130',
	water: '#6390F0',
	electric: '#F7D02C',
	grass: '#7AC74C',
	ice: '#96D9D6',
	fighting: '#C22E28',
	poison: '#A33EA1',
	ground: '#E2BF65',
	flying: '#A98FF3',
	psychic: '#F95587',
	bug: '#A6B91A',
	rock: '#B6A136',
	ghost: '#735797',
	dragon: '#6F35FC',
	dark: '#705746',
	steel: '#B7B7CE',
	fairy: '#D685AD',
};




